name: sodagarkom_app
description: "A mobile apps for sodagarkom e-commerce system."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  intl: ^0.19.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PlusJakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
  assets:
    - assets/svg/
    - assets/svg/tabsicons/
    - assets/images/
